spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bs?serverTimezone=GMT%2B8
    username: root
    password: zhw9988988
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

